apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-app-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: quay.io/your-username/backend:latest # استبدل your-username بـ username الخاص بك على Quay أو DockerHub
        ports:
        - containerPort: 5000
        env:
        - name: ENV
          value: "Production"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: my-app-prod
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
